import type { Config } from 'tailwindcss';

const config: Config = {
  content: ['./app/**/*.{ts,tsx}', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        surface: '#fbf9f4',
        'surface-dim': '#dbdad5',
        'surface-bright': '#fbf9f4',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f5f3ee',
        'surface-container': '#f0eee9',
        'surface-container-high': '#eae8e3',
        'surface-container-highest': '#e4e2dd',
        'on-surface': '#1b1c19',
        'on-surface-variant': '#57423d',
        'inverse-surface': '#30312e',
        'inverse-on-surface': '#f2f1ec',
        outline: '#8a716b',
        'outline-variant': '#dec0b9',
        'surface-tint': '#a43d22',
        primary: '#a03a20',
        'on-primary': '#ffffff',
        'primary-container': '#c15236',
        'on-primary-container': '#fffbff',
        'inverse-primary': '#ffb4a2',
        secondary: '#855402',
        'on-secondary': '#ffffff',
        'secondary-container': '#ffbd69',
        'on-secondary-container': '#774a00',
        tertiary: '#48624b',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#607b62',
        'on-tertiary-container': '#f7fff3',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#ffdad2',
        'primary-fixed-dim': '#ffb4a2',
        'on-primary-fixed': '#3c0700',
        'on-primary-fixed-variant': '#83250d',
        'secondary-fixed': '#ffddb8',
        'secondary-fixed-dim': '#fcba66',
        'on-secondary-fixed': '#2a1700',
        'on-secondary-fixed-variant': '#653e00',
        'tertiary-fixed': '#cceacc',
        'tertiary-fixed-dim': '#b1ceb1',
        'on-tertiary-fixed': '#07200e',
        'on-tertiary-fixed-variant': '#334d36',
        background: '#fbf9f4',
        'on-background': '#1b1c19',
        'surface-variant': '#f2efe9',
      },
      fontFamily: {
        serif: ['"Noto Serif SC"', 'Newsreader', 'serif'],
        sans: ['"Noto Sans SC"', '"Be Vietnam Pro"', 'sans-serif'],
        'headline-xl': ['"Noto Serif SC"', 'Newsreader', 'serif'],
        'headline-lg': ['"Noto Serif SC"', 'Newsreader', 'serif'],
        'headline-lg-mobile': ['"Noto Serif SC"', 'Newsreader', 'serif'],
        'headline-md': ['"Noto Serif SC"', 'Newsreader', 'serif'],
        'body-lg': ['"Noto Sans SC"', '"Be Vietnam Pro"', 'sans-serif'],
        'body-md': ['"Noto Sans SC"', '"Be Vietnam Pro"', 'sans-serif'],
        'label-md': ['"Noto Sans SC"', '"Be Vietnam Pro"', 'sans-serif'],
      },
      spacing: {
        gutter: '24px',
        base: '8px',
        'container-max': '1280px',
        'margin-mobile': '16px',
        'margin-desktop': '40px',
      },
      maxWidth: {
        'container-max': '1280px',
        container: '1280px',
      },
    },
  },
  plugins: [],
};

export default config;
